version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - dependencies
      - go

  - package-ecosystem: npm
    directory: /vscode
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "vscode"
      include: "scope"
    labels:
      - dependencies
      - vscode

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "container"
      include: "scope"
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - dependencies
      - ci
