blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://santosr2.github.io/TerraTidy/
    about: Check the documentation for guides and references
  - name: Discussions
    url: https://github.com/santosr2/terratidy/discussions
    about: Ask questions and discuss ideas
