# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terratidy < Formula
  desc "Terraform/Terragrunt quality platform"
  homepage "https://github.com/santosr2/terratidy"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/santosr2/terratidy/releases/download/v0.1.0/terratidy-0.1.0-darwin-amd64.tar.gz"
      sha256 "f1830d05188de3423db2d03c32631b4752aa21c8ca94098734bccd47e4c475ab"

      def install
        bin.install "terratidy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/santosr2/terratidy/releases/download/v0.1.0/terratidy-0.1.0-darwin-arm64.tar.gz"
      sha256 "331bf3c133c8084c5d9a62cb23614a4d829d9f911df7a482f40e7c74d933bb8d"

      def install
        bin.install "terratidy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/santosr2/terratidy/releases/download/v0.1.0/terratidy-0.1.0-linux-amd64.tar.gz"
      sha256 "90c1efe29eac1f71a71f1704adf7a282b1e5cad237e739a94e15cbdcdda11ceb"
      def install
        bin.install "terratidy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/santosr2/terratidy/releases/download/v0.1.0/terratidy-0.1.0-linux-arm64.tar.gz"
      sha256 "f83e74e123d8889f95fb4d57ff80d7bf5f9c9f6182ffbb941ddee9587a823017"
      def install
        bin.install "terratidy"
      end
    end
  end

  test do
    system "#{bin}/terratidy version"
  end
end
