# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terratidy < Formula
  desc "Terraform/Terragrunt quality platform"
  homepage "https://github.com/santosr2/TerraTidy"
  version "0.2.0-alpha"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/santosr2/TerraTidy/releases/download/v0.2.0-alpha/terratidy-0.2.0-alpha-darwin-amd64.tar.gz"
      sha256 "017eae9e4a6c6c0f92f3fe0555162a9c032b65a37064f0117ea9bf80901a345d"

      def install
        bin.install "terratidy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/santosr2/TerraTidy/releases/download/v0.2.0-alpha/terratidy-0.2.0-alpha-darwin-arm64.tar.gz"
      sha256 "d8a4ed0c9debdb67e270e973742964e1d7a55f61fc74adfd0db1d93968fa86a7"

      def install
        bin.install "terratidy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/santosr2/TerraTidy/releases/download/v0.2.0-alpha/terratidy-0.2.0-alpha-linux-amd64.tar.gz"
      sha256 "ef5541e0228a56426e241b05b5ba51b09aed8815f9fd9ca9b738f51c544dd970"
      def install
        bin.install "terratidy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/santosr2/TerraTidy/releases/download/v0.2.0-alpha/terratidy-0.2.0-alpha-linux-arm64.tar.gz"
      sha256 "4488ee00d5a42a1951e3afda2b4184ab9b8a752385b5234d45582443db67b34f"
      def install
        bin.install "terratidy"
      end
    end
  end

  test do
    system "#{bin}/terratidy version"
  end
end
