package output

import (
	"bytes"
	"testing"

	"github.com/hashicorp/hcl/v2"
	"github.com/santosr2/terratidy/pkg/sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMarkdownFormatter_Format(t *testing.T) {
	t.Run("empty findings shows all passed", func(t *testing.T) {
		formatter := &MarkdownFormatter{Version: "1.0.0", Title: "Test Report"}
		var buf bytes.Buffer

		err := formatter.Format([]sdk.Finding{}, &buf)
		require.NoError(t, err)

		output := buf.String()
		assert.Contains(t, output, "# Test Report")
		assert.Contains(t, output, "All checks passed")
		assert.Contains(t, output, "| **Total** | **0** |")
	})

	t.Run("includes summary table", func(t *testing.T) {
		formatter := &MarkdownFormatter{Version: "1.0.0"}
		var buf bytes.Buffer

		findings := []sdk.Finding{
			{Rule: "rule1", Message: "Error", File: "test.tf", Severity: sdk.SeverityError},
			{Rule: "rule2", Message: "Warning", File: "test.tf", Severity: sdk.SeverityWarning},
			{Rule: "rule3", Message: "Info", File: "test.tf", Severity: sdk.SeverityInfo},
		}

		err := formatter.Format(findings, &buf)
		require.NoError(t, err)

		output := buf.String()
		assert.Contains(t, output, "## Summary")
		assert.Contains(t, output, "| Errors | 1 |")
		assert.Contains(t, output, "| Warnings | 1 |")
		assert.Contains(t, output, "| Info | 1 |")
		assert.Contains(t, output, "| **Total** | **3** |")
	})

	t.Run("groups findings by file", func(t *testing.T) {
		formatter := &MarkdownFormatter{Version: "1.0.0"}
		var buf bytes.Buffer

		findings := []sdk.Finding{
			{Rule: "rule1", Message: "Error in file1", File: "file1.tf", Severity: sdk.SeverityError},
			{Rule: "rule2", Message: "Warning in file2", File: "file2.tf", Severity: sdk.SeverityWarning},
		}

		err := formatter.Format(findings, &buf)
		require.NoError(t, err)

		output := buf.String()
		assert.Contains(t, output, "### `file1.tf`")
		assert.Contains(t, output, "### `file2.tf`")
	})

	t.Run("includes severity icons", func(t *testing.T) {
		formatter := &MarkdownFormatter{Version: "1.0.0"}
		var buf bytes.Buffer

		findings := []sdk.Finding{
			{Rule: "rule1", Message: "Error", File: "test.tf", Severity: sdk.SeverityError},
			{Rule: "rule2", Message: "Warning", File: "test.tf", Severity: sdk.SeverityWarning},
			{Rule: "rule3", Message: "Info", File: "test.tf", Severity: sdk.SeverityInfo},
		}

		err := formatter.Format(findings, &buf)
		require.NoError(t, err)

		output := buf.String()
		assert.Contains(t, output, ":x:")
		assert.Contains(t, output, ":warning:")
		assert.Contains(t, output, ":information_source:")
	})

	t.Run("includes line numbers", func(t *testing.T) {
		formatter := &MarkdownFormatter{Version: "1.0.0"}
		var buf bytes.Buffer

		findings := []sdk.Finding{
			{
				Rule:     "test.rule",
				Message:  "Test message",
				File:     "test.tf",
				Location: hcl.Range{Start: hcl.Pos{Line: 42, Column: 5}},
				Severity: sdk.SeverityWarning,
			},
		}

		err := formatter.Format(findings, &buf)
		require.NoError(t, err)

		output := buf.String()
		assert.Contains(t, output, "| 42 |")
	})

	t.Run("includes version in footer", func(t *testing.T) {
		formatter := &MarkdownFormatter{Version: "1.2.3", Title: "Test Report"}
		var buf bytes.Buffer

		findings := []sdk.Finding{
			{Rule: "rule", Message: "Test", File: "test.tf", Severity: sdk.SeverityInfo},
		}

		err := formatter.Format(findings, &buf)
		require.NoError(t, err)

		output := buf.String()
		assert.Contains(t, output, "*Generated by TerraTidy 1.2.3*")
	})

	t.Run("escapes pipe characters in messages", func(t *testing.T) {
		formatter := &MarkdownFormatter{Version: "1.0.0"}
		var buf bytes.Buffer

		findings := []sdk.Finding{
			{
				Rule:     "test.rule",
				Message:  "Message with | pipe",
				File:     "test.tf",
				Severity: sdk.SeverityWarning,
			},
		}

		err := formatter.Format(findings, &buf)
		require.NoError(t, err)

		output := buf.String()
		assert.Contains(t, output, "\\|")
	})

	t.Run("uses default title when not specified", func(t *testing.T) {
		formatter := &MarkdownFormatter{Version: "1.0.0"}
		var buf bytes.Buffer

		err := formatter.Format([]sdk.Finding{}, &buf)
		require.NoError(t, err)

		output := buf.String()
		assert.Contains(t, output, "# TerraTidy Report")
	})
}

func TestEscapeMarkdown(t *testing.T) {
	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{"no special chars", "hello world", "hello world"},
		{"pipe character", "a | b", "a \\| b"},
		{"newline", "line1\nline2", "line1 line2"},
		{"carriage return", "line1\rline2", "line1line2"},
		{"multiple pipes", "a|b|c", "a\\|b\\|c"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := escapeMarkdown(tt.input)
			assert.Equal(t, tt.expected, result)
		})
	}
}
