package output

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/santosr2/TerraTidy/pkg/sdk"
)

// MarkdownFormatter outputs findings as a Markdown summary.
// This format is ideal for PR comments, GitHub Actions summaries, and documentation.
type MarkdownFormatter struct {
	Version       string
	Title         string
	AbsolutePaths bool
}

// Format implements the Formatter interface for Markdown output
func (f *MarkdownFormatter) Format(findings []sdk.Finding, w io.Writer) error {
	title := f.Title
	if title == "" {
		title = "TerraTidy Report"
	}

	// Count by severity
	var errors, warnings, info int
	for _, finding := range findings {
		switch finding.Severity {
		case sdk.SeverityError:
			errors++
		case sdk.SeverityWarning:
			warnings++
		case sdk.SeverityInfo:
			info++
		}
	}

	// Write header
	_, _ = fmt.Fprintf(w, "# %s\n\n", title)

	// Write summary section
	f.writeSummary(w, len(findings), errors, warnings, info)

	// Write findings
	if len(findings) == 0 {
		_, _ = fmt.Fprintln(w, "No issues found. All checks passed.")
		return nil
	}

	// Group findings by file
	byFile := make(map[string][]sdk.Finding)
	for _, finding := range findings {
		byFile[finding.File] = append(byFile[finding.File], finding)
	}

	// Sort files for consistent output
	var files []string
	for file := range byFile {
		files = append(files, file)
	}
	sort.Strings(files)

	// Write findings by file
	_, _ = fmt.Fprint(w, "\n## Findings\n\n")
	for _, file := range files {
		f.writeFileFindingsAsTable(w, file, byFile[file])
	}

	// Write footer
	if f.Version != "" {
		_, _ = fmt.Fprintf(w, "\n---\n*Generated by TerraTidy %s*\n", f.Version)
	}

	return nil
}

func (f *MarkdownFormatter) writeSummary(w io.Writer, total, errors, warnings, info int) {
	_, _ = fmt.Fprint(w, "## Summary\n\n")
	_, _ = fmt.Fprint(w, "| Severity | Count |\n")
	_, _ = fmt.Fprint(w, "|----------|-------|\n")
	_, _ = fmt.Fprintf(w, "| Errors | %d |\n", errors)
	_, _ = fmt.Fprintf(w, "| Warnings | %d |\n", warnings)
	_, _ = fmt.Fprintf(w, "| Info | %d |\n", info)
	_, _ = fmt.Fprintf(w, "| **Total** | **%d** |\n", total)
}

func (f *MarkdownFormatter) writeFileFindingsAsTable(w io.Writer, file string, findings []sdk.Finding) {
	displayFile := DisplayPath(file, f.AbsolutePaths)
	_, _ = fmt.Fprintf(w, "### `%s`\n\n", displayFile)
	_, _ = fmt.Fprint(w, "| Severity | Line | Rule | Message |\n")
	_, _ = fmt.Fprint(w, "|----------|------|------|---------|")

	for _, finding := range findings {
		icon := f.severityIcon(finding.Severity)
		_, _ = fmt.Fprintf(
			w, "\n| %s %s | %d | `%s` | %s |",
			icon,
			finding.Severity,
			finding.Location.StartLine,
			finding.Rule,
			escapeMarkdown(finding.Message),
		)
	}
	_, _ = fmt.Fprint(w, "\n\n")
}

func (f *MarkdownFormatter) severityIcon(severity sdk.Severity) string {
	switch severity {
	case sdk.SeverityError:
		return ":x:"
	case sdk.SeverityWarning:
		return ":warning:"
	case sdk.SeverityInfo:
		return ":information_source:"
	default:
		return ""
	}
}

// escapeMarkdown escapes special markdown characters in strings
func escapeMarkdown(s string) string {
	// Escape pipe characters which would break table formatting
	var b strings.Builder
	b.Grow(len(s))
	for _, c := range s {
		switch c {
		case '|':
			b.WriteString("\\|")
		case '\n':
			b.WriteByte(' ')
		case '\r':
			// Skip carriage returns
		default:
			b.WriteRune(c)
		}
	}
	return b.String()
}
