// Package buildinfo provides version and build information for TerraTidy.
// It uses go:embed to include version info from a file generated at build time,
// with fallback to ldflags and runtime/debug for development builds.
package buildinfo

import (
	_ "embed"
	"encoding/json"
	"runtime/debug"
)

// Build information set via ldflags at build time
var (
	Version = "dev"
	Commit  = "none"
	Date    = "unknown"
)

// versionFile contains version info generated at build time.
// This file is optional - if not present, we fall back to ldflags or debug info.
//
//go:embed version.json
var versionFile []byte

// versionInfo holds the parsed version information
type versionInfo struct {
	Version string `json:"version"`
	Commit  string `json:"commit"`
	Date    string `json:"date"`
}

func init() {
	// Priority 1: Try embedded version file (generated by goreleaser)
	if len(versionFile) > 0 {
		var info versionInfo
		if err := json.Unmarshal(versionFile, &info); err == nil {
			if info.Version != "" {
				Version = info.Version
			}
			if info.Commit != "" {
				Commit = info.Commit
			}
			if info.Date != "" {
				Date = info.Date
			}
			return
		}
	}

	// Priority 2: ldflags already set (non-dev version)
	if Version != "dev" {
		return
	}

	// Priority 3: runtime/debug for go install or local builds
	if info, ok := debug.ReadBuildInfo(); ok {
		// Get module version (e.g., v0.1.0)
		if info.Main.Version != "" && info.Main.Version != "(devel)" {
			Version = info.Main.Version
		}

		// Get VCS info from build settings
		for _, setting := range info.Settings {
			switch setting.Key {
			case "vcs.revision":
				if len(setting.Value) >= 7 {
					Commit = setting.Value[:7]
				} else if setting.Value != "" {
					Commit = setting.Value
				}
			case "vcs.time":
				if setting.Value != "" {
					Date = setting.Value
				}
			case "vcs.modified":
				if setting.Value == "true" && Commit != "none" {
					Commit += "-dirty"
				}
			}
		}
	}
}

// GetVersion returns the version string.
func GetVersion() string {
	return Version
}
